"use client";

import Link from "next/link";
import { FormEvent, useState } from "react";

export default function Home() {
  const [sent, setSent] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); setError(""); try { const form = Object.fromEntries(new FormData(event.currentTarget)); const response = await fetch("/api/inquiries", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(form) }); if (!response.ok) return setError("Impossible d’envoyer la demande. Réessayez dans un instant."); setSent(true); event.currentTarget.reset(); } catch { setError("La connexion a été interrompue. Vérifiez votre réseau puis réessayez."); } finally { setBusy(false); } };
  return <main className="marketing-page"><header className="marketing-nav"><Link href="/" className="brand"><span>♧</span><b>CALM <em>by Angèle</em></b></Link><div className="flex gap-4"><Link href="/prestations" className="marketing-login">Prestations</Link><Link href="/login" className="marketing-login">Espace équipe →</Link></div></header>
    <section className="marketing-hero"><div><p className="eyebrow">Conciergerie canine · Bourbourg</p><h1>Comme à la maison,<br /><i>avec beaucoup d’attention.</i></h1><p>Des gardes pensées autour du rythme, des habitudes et du bien-être de chaque compagnon.</p><a className="calm-primary" href="#demande">Demander une garde <span>→</span></a></div><div className="hero-art"><div className="hero-paw">♧</div><p>Chaque animal a sa place ici.</p></div></section>
    <section className="trust-grid"><article><b>Un accueil sur mesure</b><p>Un seul foyer, des repères et beaucoup de douceur.</p></article><article><b>Des nouvelles sincères</b><p>Photos, petits mots et album privé pendant le séjour.</p></article><article><b>Une relation de confiance</b><p>Un dossier clair, des habitudes respectées, aucun détail oublié.</p></article></section>
    <section className="marketing-story"><div className="story-mark">◌</div><div><p className="eyebrow">L’esprit CALM</p><h2>Prendre soin, c’est aussi vous rassurer.</h2><p>Avant chaque séjour, nous prenons le temps de faire connaissance. Alimentation, rythme, petites habitudes ou besoins particuliers : tout compte pour que votre compagnon se sente attendu.</p></div></section>
    <section className="marketing-faq"><div><p className="eyebrow">Avant de nous écrire</p><h2>Les premières réponses.</h2><p>Parce qu’un premier séjour se prépare aussi avec confiance.</p></div><div className="faq-list"><details open><summary>Comment faire une demande de garde ?</summary><p>Remplissez le formulaire ci-dessous avec les dates et les besoins de votre compagnon. Angèle vous répond personnellement sous 48 h ouvrées.</p></details><details><summary>Mon animal a des besoins particuliers, est-ce possible ?</summary><p>Oui : indiquez ses habitudes, son alimentation ou son traitement lors de votre demande. Chaque accueil est préparé avec soin.</p></details><details><summary>Aurai-je des nouvelles pendant le séjour ?</summary><p>Oui. Des petits mots et des souvenirs peuvent être ajoutés à l’album privé de votre compagnon pendant son séjour.</p></details></div></section>
    <section id="demande" className="inquiry-section"><div><p className="eyebrow">Premier contact</p><h2>Parlons de votre compagnon.</h2><p>Quelques informations suffisent pour étudier votre demande. Angèle vous répondra personnellement.</p><div className="contact-note">Bourbourg et alentours<br /><span>Réponse sous 48 h ouvrées</span></div></div><form onSubmit={submit} className="inquiry-form">{sent && <p className="success-message">Merci, votre demande est bien arrivée. À très vite !</p>}<label>Votre prénom et nom<input required name="name" placeholder="Ex. Camille Martin" /></label><label>Votre e-mail<input required type="email" name="email" placeholder="vous@exemple.fr" /></label><label>Votre téléphone<input name="phone" type="tel" placeholder="Facultatif" /></label><label>Votre compagnon<input name="pet" placeholder="Prénom, espèce, âge…" /></label><label>Dates souhaitées<input name="dates" placeholder="Ex. du 12 au 16 juillet" /></label><label className="full">Dites-nous en un peu plus<textarea required name="message" rows={4} placeholder="Type de garde, habitudes, besoins particuliers…" /></label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" /><button disabled={busy} className="calm-primary full">{busy ? "Envoi…" : "Envoyer ma demande"} <span>→</span></button>{error && <p className="form-error full">{error}</p>}</form></section>
    <footer className="marketing-footer"><span>CALM by Angèle · Conciergerie canine</span><Link href="/login">Connexion équipe</Link></footer>
  </main>;
}
