"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { auth } from "@/lib/firebase";

export default function ClientPhotos() {
  const [photos, setPhotos] = useState<any[]>([]); const [comments, setComments] = useState<any[]>([]); const [drafts, setDrafts] = useState<Record<string, string>>({}); const [status, setStatus] = useState("");
  const load = async () => { const token = await auth.currentUser?.getIdToken(); const r = await fetch("/api/client/portal", { headers: { Authorization: `Bearer ${token}` } }); if (r.ok) { const data = await r.json(); setPhotos(data.photos); setComments(data.comments || []); } };
  useEffect(() => { void load(); }, []);
  const send = async (photoId: string) => { const message = drafts[photoId]?.trim(); if (!message) return; setStatus(""); const token = await auth.currentUser?.getIdToken(true); const r = await fetch("/api/client/photo-comments", { method: "POST", headers: { "Content-Type": "application/json", Authorization: `Bearer ${token}` }, body: JSON.stringify({ photoId, message }) }); if (!r.ok) return setStatus("Votre message n’a pas pu être envoyé."); setDrafts({ ...drafts, [photoId]: "" }); setStatus("Votre petit mot a bien été transmis à Angèle."); await load(); };
  return <main className="public-calm min-h-screen p-5"><header className="mx-auto flex max-w-5xl justify-between"><Link href="/client" className="brand"><span>♧</span><b>CALM <em>by Angèle</em></b></Link><Link href="/client" className="marketing-login">Mon espace</Link></header><section className="mx-auto mt-10 max-w-5xl"><p className="eyebrow">Les souvenirs</p><h1 className="gallery-title">Les moments de garde.</h1><p className="mt-3 max-w-xl text-sm text-[#68776e]">Un album privé, simplement pour vous donner des nouvelles. Vous pouvez laisser un petit mot sous chaque souvenir.</p>{status && <p className="success-message mt-5">{status}</p>}<div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{photos.map((photo) => <article key={photo.id} className="gallery-photo"><img src={photo.imageUrl} alt={photo.caption || "Souvenir de garde"} />{photo.caption && <p>{photo.caption}</p>}<div className="photo-comments">{comments.filter((comment) => comment.photoId === photo.id).map((comment) => <p key={comment.id}>♡ {comment.message}</p>)}</div><div className="photo-comment-form"><input aria-label="Laisser un message" placeholder="Un petit mot pour Angèle…" value={drafts[photo.id] || ""} onChange={(e) => setDrafts({ ...drafts, [photo.id]: e.target.value })} /><button onClick={() => void send(photo.id)}>Envoyer</button></div></article>)}</div>{!photos.length && <p className="empty-state mt-7">Les premiers souvenirs arriveront ici pendant les séjours.</p>}</section></main>;
}
