"use client";

import { useEffect, useState } from "react";
import { auth } from "@/lib/firebase";

type Inquiry = { id: string; name: string; email: string; phone?: string; pet?: string; dates?: string; message: string; status: "nouvelle" | "contactée" | "archivée" };
export default function RequestsPage() {
  const [items, setItems] = useState<Inquiry[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState("");
  const token = async () => auth.currentUser?.getIdToken();
  const load = async () => { setLoading(true); setError(""); try { const idToken = await token(); const response = await fetch("/api/inquiries/admin", { headers: idToken ? { Authorization: `Bearer ${idToken}` } : {} }); if (!response.ok) throw new Error(); const data = await response.json(); setItems(data.items.sort((a: Inquiry, b: Inquiry) => (a.status === "nouvelle" ? -1 : 1))); } catch { setError("Impossible de charger les demandes pour le moment."); } finally { setLoading(false); } };
  useEffect(() => { load(); }, []);
  const setStatus = async (id: string, status: Inquiry["status"]) => { try { const idToken = await token(); const response = await fetch("/api/inquiries/admin", { method: "PATCH", headers: { "Content-Type": "application/json", ...(idToken ? { Authorization: `Bearer ${idToken}` } : {}) }, body: JSON.stringify({ id, status }) }); if (!response.ok) throw new Error(); setItems((current) => current.map((item) => item.id === id ? { ...item, status } : item)); } catch { setError("La demande n’a pas pu être mise à jour."); } };
  return <div className="space-y-8"><header className="page-intro"><div><p className="eyebrow">Premier contact</p><h1>Les demandes de garde.</h1><p>Les nouvelles demandes arrivent ici, prêtes à être traitées en douceur.</p></div><span className="page-count">{items.filter((item) => item.status === "nouvelle").length} nouvelle{items.filter((item) => item.status === "nouvelle").length > 1 ? "s" : ""}</span></header><section className="space-y-3">{loading && <div className="empty-state">Chargement des demandes…</div>}{error && <div className="empty-state">{error}</div>}{items.map((item) => <article key={item.id} className="request-card"><div className="flex-1"><div className="flex flex-wrap items-center gap-2"><h2>{item.name}</h2><span className={`request-status ${item.status}`}>{item.status}</span></div><p className="mt-2 text-sm text-[#4e6258]"><b>{item.pet || "Compagnon à préciser"}</b>{item.dates && ` · ${item.dates}`}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-6 text-[#718078]">{item.message}</p><div className="mt-4 flex flex-wrap gap-3 text-sm font-semibold text-[#315e4e]"><a href={`mailto:${item.email}`}>Écrire à {item.email}</a>{item.phone && <a href={`tel:${item.phone}`}>Appeler {item.phone}</a>}</div></div><div className="flex gap-2"><button onClick={() => setStatus(item.id, "contactée")} className="request-action">Contactée</button><button onClick={() => setStatus(item.id, "archivée")} className="request-action">Archiver</button></div></article>)}{!loading && !items.length && !error && <div className="empty-state">Aucune demande pour le moment.</div>}</section></div>;
}
