"use client";

import { useEffect, useState } from "react";
import { useParams } from "next/navigation";

type Booking = { id: string; dateDebut: string; dateFin: string; nombreNuits?: number };
type Photo = { id: string; bookingId: string; imageUrl: string; caption: string; category?: "balade" | "jeu" | "repas" | "repos" | "moment"; createdAt: string | null };
type Gallery = { dog: { nom: string; race: string; dateNaissance: string; photoProfil: string | null }; bookings: Booking[]; photos: Photo[] };
const categoryLabels = { balade: "Balade", jeu: "Jeu", repas: "Repas", repos: "Repos", moment: "Joli moment" };

export default function DogPublicPage() {
  const { slug } = useParams<{ slug: string }>(); const [code, setCode] = useState(""); const [gallery, setGallery] = useState<Gallery | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [activeImage, setActiveImage] = useState<string | null>(null);
  const loadGallery = async () => { const response = await fetch(`/api/gallery/${encodeURIComponent(slug)}`, { cache: "no-store" }); if (!response.ok) return false; setGallery(await response.json()); return true; };
  useEffect(() => { const timer = window.setTimeout(() => { void loadGallery().finally(() => setLoading(false)); }, 0); return () => window.clearTimeout(timer); }, [slug]);
  const unlock = async () => { setError(""); const response = await fetch("/api/gallery/access", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ slug, code }) }); if (!response.ok) return setError("Ce code ne semble pas correspondre. Vérifiez l’e-mail reçu."); setLoading(true); if (!(await loadGallery())) setError("La galerie est momentanément indisponible."); setLoading(false); };
  if (loading) return <main className="public-calm grid min-h-screen place-items-center"><div className="loading-mark">♧</div></main>;
  if (!gallery) return <main className="public-calm grid min-h-screen place-items-center px-5"><section className="access-card"><span className="pet-seal">♧</span><p className="eyebrow">Album privé</p><h1>Les souvenirs sont bien gardés.</h1><p>Entrez le code transmis par Angèle pour découvrir l’album de séjour de votre compagnon.</p><label className="calm-label mt-7">Code d’accès<input aria-label="Code d’accès" type="password" value={code} onChange={(event) => setCode(event.target.value)} onKeyDown={(event) => event.key === "Enter" && unlock()} autoFocus /></label>{error && <p className="mt-3 text-sm text-[#b5533a]" role="alert">{error}</p>}<button onClick={unlock} className="calm-primary mt-6 w-full">Découvrir l’album <span>→</span></button><small className="mt-6 block text-center text-[#849088]">Espace personnel et confidentiel</small></section></main>;
  return <main className="public-calm min-h-screen px-5 py-10 sm:px-8"><header className="mx-auto max-w-5xl text-center"><span className="pet-seal">♧</span><p className="eyebrow mt-5">L’album de {gallery.dog.nom}</p><h1 className="gallery-title">Des nouvelles qui font du bien.</h1><p className="mx-auto mt-3 max-w-lg text-sm leading-6 text-[#64766c]">Tous les petits instants d’un séjour heureux, réunis ici avec soin.</p></header>
    <section className="pet-profile mx-auto mt-9 max-w-5xl">{gallery.dog.photoProfil ? <img src={gallery.dog.photoProfil} alt={gallery.dog.nom} /> : <span className="profile-placeholder">◌</span>}<div><p className="eyebrow">Votre compagnon</p><h2>{gallery.dog.nom}</h2><p>{gallery.dog.race || "Compagnon adoré"}</p></div><span className="ml-auto hidden rounded-full bg-[#e2eee6] px-3 py-1 text-xs font-bold text-[#315e4e] sm:block">Album privé</span></section>
    <section className="mx-auto mt-7 max-w-5xl space-y-6">{gallery.bookings.map((booking) => { const photos = gallery.photos.filter((photo) => photo.bookingId === booking.id); return <article key={booking.id} className="gallery-stay"><div className="flex flex-wrap items-start justify-between gap-3"><div><p className="eyebrow">Séjour</p><h2>Du {booking.dateDebut} au {booking.dateFin}</h2></div><span className="photo-count">{photos.length} souvenir{photos.length > 1 ? "s" : ""}</span></div><div className="mt-6 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3">{photos.map((photo) => <button key={photo.id} onClick={() => setActiveImage(photo.imageUrl)} className="gallery-photo"><div className="gallery-image-wrap"><img src={photo.imageUrl} alt={photo.caption || `Souvenir de ${gallery.dog.nom}`} /><span className="gallery-category">{categoryLabels[photo.category ?? "moment"]}</span></div>{photo.caption && <p>{photo.caption}</p>}</button>)}</div>{photos.length === 0 && <p className="empty-state mt-6">Les premiers souvenirs de ce séjour arriveront bientôt.</p>}</article>; })}</section>
    {activeImage && <button className="fixed inset-0 z-50 grid place-items-center bg-[#15271f]/90 p-4" aria-label="Fermer l’image" onClick={() => setActiveImage(null)}><img src={activeImage} alt="Souvenir agrandi" className="max-h-[90vh] max-w-full rounded-3xl shadow-2xl" /></button>}
  </main>;
}
